version: "3.3"

services:
  app_test:
    build: .
    image: 'nb4444-dev-api-test'
    command: sh -c "python manage.py migrate && python manage.py collectstatic --noinput && python manage.py test -v 2"