# Generated by Django 3.1.13 on 2021-10-24 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency("auth.User"),
        ('B4', '0002_note_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultdeductions',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
