# Generated by Django 3.1.13 on 2021-11-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B4', '0003_defaultdeductions_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultdeductions',
            name='food',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Еда'),
        ),
        migrations.AlterField(
            model_name='defaultdeductions',
            name='house',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Жильё'),
        ),
        migrations.AlterField(
            model_name='defaultdeductions',
            name='phone',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='defaultdeductions',
            name='travel',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Проезд'),
        ),
        migrations.AlterField(
            model_name='note',
            name='image',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='foto/%Y/%m/%d', verbose_name='Фотоверсия'),
        ),
    ]
