# Generated by Django 3.1.13 on 2021-11-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B4', '0004_auto_20211107_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='foto/%Y/%m/%d', verbose_name='Фотоверсия'),
        ),
    ]
