# Generated by Django 3.1.13 on 2022-04-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B4', '0006_auto_20220409_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultdeductions',
            name='delete_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='note',
            name='delete_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='plan',
            name='delete_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='task',
            name='delete_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AlterField(
            model_name='defaultdeductions',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Удалено'),
        ),
        migrations.AlterField(
            model_name='note',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Удалено'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Удалено'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Удалено'),
        ),
    ]
