# Generated by Django 3.1.13 on 2022-04-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B4', '0007_auto_20220409_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaulttasks',
            name='is_ready',
            field=models.BooleanField(default=False, verbose_name='Выполнено'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_ready',
            field=models.BooleanField(default=False, verbose_name='Выполнено'),
        ),
    ]
