# Generated by Django 3.1.14 on 2022-12-20 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B4', '0009_auto_20221218_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High'), (3, 'Hot')], default=1, verbose_name='Приоритет'),
        ),
        migrations.DeleteModel(
            name='DefaultTasks',
        ),
    ]
