# Generated by Django 3.1.14 on 2022-12-20 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('B4', '0010_auto_20221221_0102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['is_ready', '-priority', '-updated_at', '-created_at', '-id'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
