# Generated by Django 3.1.14 on 2022-12-24 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('B4', '0011_auto_20221221_0134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
