# Generated by Django 3.1.14 on 2023-10-22 18:08

from django.db import migrations, transaction


def create_default_value(apps, schema_editor):
    section_class = apps.get_model("B4", "section")
    with transaction.atomic():
        section = section_class(name='Основной', is_active=True)
        section.save()


class Migration(migrations.Migration):

    dependencies = [
        ('B4', '0014_auto_20221230_1100'),
    ]

    operations = [
        migrations.RunPython(create_default_value, reverse_code=migrations.RunPython.noop),
    ]
