# Generated by Django 3.1.14 on 2023-10-22 18:22

from django.db import migrations, transaction
from django.contrib.auth.hashers import make_password


def create_default_value(apps, schema_editor):
    user_class = apps.get_model("B4", "user")
    if user_class.objects.filter(username="admin",).exists():
        return
    with transaction.atomic():
        user = user_class.objects.create(
            username="admin",
            email="admin@example.com",
            password=make_password("55555"),
            is_active=True,
            is_staff=True,
            is_superuser=True,
        )
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('B4', '0016_auto_20231022_2118'),
    ]

    operations = [
        migrations.RunPython(create_default_value, reverse_code=migrations.RunPython.noop),
    ]
